stages:
  - build
  # - test
  - deliver

variables:
  MONGO_DB_URL: 'mongodb+srv://gustavwvjohansson:kBEpmXAUtCaPuAkP@refridgecluster.fieialy.mongodb.net/'
  NODE_ENV: 'production'

cache:
  paths:
    - backend/node_modules/
    - frontend/node_modules/

services:
  - name: mongo:latest
    alias: mongo

build_backend:
  stage: build
  image: node:14-alpine
  script:
    - npm install -g eslint 
    - npm install -g prettier
    - cd backend && npm install
    - npm run lint
    - npm run format
# build_frontend:
#   stage: build
#   image: node:14-alpine
#   script:
#     - npm install -g eslint 
#     - npm install -g prettier
#     - cd frontend && npm install
#     - npm run lint
#     - npm run format
# test_api:
#   stage: test
#   image: node:14-alpine
#   variables:
#     MONGO_DB_URL: ${MONGO_DB_URL}
#   services:
#     - name: mongo:latest # add MongoDB container definition
#       alias: mongo
#   before_script:
#     - cd frontend
#     - npm install
#     - npm start &
#     - sleep 10 # wait for MongoDB to start
#   script:
#     - npm run test
#     - npm install -g newman
#     - newman run tests/api_test/postman_collection.json

deliver:
  stage: deliver
  image: docker:latest
  services:
    - name: docker:dind
    - name: mongo:latest
      alias: mongo
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:latest -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_PROJECT_DIR
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  environment:
    name: production
  # only:
  #   - master
