on:
  push:
    branches:
      - main

jobs:
  mirror-and-ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Mirror to GitLab
      uses: SvanBoxel/gitlab-mirror-and-ci-action@v2
      with:
        args: "https://gitlab.com/mary.maksemos/refridge22"
        follow-tags: false
        force-push: false
        gitlab-hostname: "gitlab.com"
        gitlab-username: "mary.maksemos"
        gitlab-password: ${{ secrets.GITLAB_PASSWORD }}
        gitlab-project-id: "45701698"
        github-token: ${{ secrets.MY_GITHUB_TOKEN }}
    - name: Trigger GitLab pipeline
      uses: SvanBoxel/gitlab-pipeline-trigger@v1
      with:
        gitlab-hostname: "gitlab.com"
        gitlab-username: "mary.maksemos"
        gitlab-token: ${{ secrets.GITLAB_TOKEN }}
        project-id: "mary.maksemos/refridge22"
        ref: "main"
