name: Mirror and run GitLab CI

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Mirror + trigger CI
        uses: SvanBoxel/gitlab-mirror-and-ci-action@master
        with:
          args: "https://gitlab.com/mary.maksemos/refridge22"
        env:
          FOLLOW_TAGS: "false"
          FORCE_PUSH: "false"
          GITLAB_HOSTNAME: "gitlab.com"
          GITLAB_USERNAME: "mary.maksemos"
          GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
          GITLAB_PROJECT_ID: "45701698"
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
