name: Mirror and run GitLab CI
on:
  push:
    branches:
      - develop
      - main 
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Mirror + trigger CI
        uses: SvanBoxel/gitlab-mirror-and-ci-action@master
        with:
          args: "https://gitlab.com/mary.maksemos/refridge"

        env:
          FOLLOW_TAGS: "false"
          FORCE_PUSH: "false"
          GITLAB_HOSTNAME: "gitlab.com"
          GITLAB_USERNAME: "mary.maksemos"
          GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }} 
          GITLAB_PROJECT_ID: "46125659" 
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
