name: SMS Notification
on:
  push:
    branches:
      - main

jobs:
  send_sms:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install twilio

      - name: Send SMS notification
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          PHONE_NUMBER: '+1234567890'  # Replace with the destination phone number
        run: |
          python - <<EOF
          from twilio.rest import Client
          import os

          account_sid = os.environ['TWILIO_ACCOUNT_SID']
          auth_token = os.environ['TWILIO_AUTH_TOKEN']
          phone_number = os.environ['PHONE_NUMBER']

          client = Client(account_sid, auth_token)
          message = client.messages.create(
              body="Pipeline Notification: Repository - Branch - Commit",
              from_=phone_number,
              to=phone_number
          )
          EOF
