name: WhatsApp Notification
on:
  push:
    branches:
      - main

jobs:
  send_whatsapp:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install twilio

      - name: Send WhatsApp notification
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          FROM_PHONE_NUMBER: 'whatsapp:+46737796897'  
          TO_PHONE_NUMBER: 'whatsapp:+46729141642'    
        run: |
          python - <<EOF
          from twilio.rest import Client
          import os

          account_sid = os.environ['TWILIO_ACCOUNT_SID']
          auth_token = os.environ['TWILIO_AUTH_TOKEN']
          from_phone_number = os.environ['FROM_PHONE_NUMBER']
          to_phone_number = os.environ['TO_PHONE_NUMBER']

          client = Client(account_sid, auth_token)
          message = client.messages.create(
              body="Pipeline Notification: Repository - Branch - Commit",
              from_=from_phone_number,
              to=to_phone_number
          )
          EOF
